# -*- coding: utf-8 -*-
"""Practica8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eW1cLmknm2dchNbn9wgzpmWn2xEZBqFr
"""

var = 2
while(var != "5"):
  print("Elige una opcion")
  var=input("")
  if(var=="1"):
    var1=int(input("dame un numero"))
    var2=int(input("dame otro numero"))
    print(var1+var2)
  elif(var=="2"):
    var1=int(input("dame un numero"))
    var2=int(input("dame otro numero"))
    print(var1*var2)
  elif(var=="3"):
    var1=int(input("dame un numero"))
    var2=int(input("dame otro numero"))
    print(var1-var2)
  elif(var==4):
    var1=int(input("dame un numero"))
    var2=int(input("dame otro numero"))
    print(var1/var2)